# (name, city, email)
# If you would like to add to this list, please let me know at alandgton@gmail.com
# Currently mayors and city council members

county_list = [
        ( "Mayor Eric Garcetti", "LA", "mayor.helpdesk@lacity.org" ),
        ( "City Attorney Mike Feuer", "LA", "mayor.garcetti@lacity.org" ), ( "Councilmember Nury Martinez", "LA", "councilmember.martinez@lacity.org"),
        ( "Councilmember Gil Cedillo", "LA", "councilmember.cedillo@lacity.org"),
        ( "Councilmember Paul Krekorian", "LA", "councilmember.Krekorian@lacity.org"),
        ( "Councilmember Bob Blumenfield", "LA", "councilmember.blumenfield@lacity.org"),
        ( "Councilmember David E. Ryu", "LA", "david.ryu@lacity.org"),

        ( "Mayor London N. Breed", "SF", "MayorLondonBreed@sfgov.org"),
        ( "Supervisor Matt Haney", "SF", "Matt.Haney@sfgov.org"),
        ( "Supervisor Rafael Mandelman", "SF", "MandelmanStaff@sfgov.org"),
        ( "Supervisor Gordon Mar", "SF", "Gordon.Mar@sfgov.org"),
        ( "Supervisor Aaron Peskin", "SF", "Aaron.Peskin@sfgov.org"),
        ( "Supervisor Dean Preston", "SF", "Dean.Preston@sfgov.org"),
        ( "Supervisor Sandra Lee Fewer", "SF", "sandra.fewer@sfgov.org"),
        ( "Supervisor Hillary Ronen", "SF", "Hillary.Ronen@sfgov.org"),
        ( "Supervisor Ahsha Safai", "SF", "Ahsha.Safai@sfgov.org"),
        ( "Supervisor Catherine Stefani", "SF", "Catherine.Stefani@sfgov.org"),
        ( "Supervisor Shamann Walton", "SF", "Shamann.Walton@sfgov.org"),
        ( "Supervisor Norman Yee", "SF", "Norman.Yee@sfgov.org"),

        ( "Mayor Sam Liccardo", "SJ", "mayoremail@sanjoseca.gov"),
        ( "Vice Mayor Charles Jones", "SJ", "District1@sanjoseca.gov"),
        ( "Councilmember Sergio Jimenez", "SJ", "District2@sanjoseca.gov"),
        ( "Councilmember Raul Peralez", "SJ", "District3@sanjoseca.gov"),
        ( "Councilmember Lan Diep", "SJ", "District4@sanjoseca.gov"),
        ( "Councilmember Magdalena Carrasco", "SJ", "District5@sanjoseca.gov"),
        ( "Councilmember Devora Davis", "SJ", "District6@sanjoseca.gov"),
        ( "Councilmember Maya Esparza", "SJ", "District7@sanjoseca.gov"),
        ( "Councilmember Sylvia Arenas", "SJ", "District8@sanjoseca.gov"),
        ( "Councilmember Pam Foley", "SJ", "District9@sanjoseca.gov"),
        ( "Councilmember Johnny Khamis", "SJ", "District10@sanjoseca.gov"),

        ( "Mayor Martin Walsh", "BOS", "mayor@boston.gov"),
        ( "Councilmember Annissa Essaibi George", "BOS", "A.E.George@boston.gov"),
        ( "Councilmember Michael Flaherty", "BOS", "Michael.F.Flaherty@boston.gov"),
        ( "Councilmember Michelle Wu", "BOS", "Michelle.Wu@boston.gov"),
        ( "Councilmember Lydia Edwards", "BOS", "lydia.edwards@boston.gov"),
        ( "Councilmember Ed Flynn", "BOS", "ed.flynn@boston.gov"),
        ( "Councilmember Frank Baker", "BOS", "Frank.Baker@boston.gov"),
        ( "Councilmember Andrea Campbell", "BOS", "Andrea.Campbell@boston.gov"),
        ( "Councilmember Ricardo Arroyo", "BOS", "ricardo.arroyo@boston.gov"),
        ( "Councilmember Matt O'Malley", "BOS", "matthew.omalley@boston.gov"),
        ( "Councilmember Kenzie Bok", "BOS", "kenzie.bok@boston.gov"),

        ( "Mayor Muriel Bowser", "DC", "eom@dc.gov"),
        ( "Chairman Phil Mendelson", "DC", "pmendelson@dccouncil.us"),
        ( "Councilmember Kenyan McDuffie", "DC", "kmcduffie@dccouncil.us"),
        ( "Councilmember Anita Bonds", "DC", "abonds@dccouncil.us"),
        ( "Councilmember David Grosso", "DC", "dgrosso@dccouncil.us"),
        ( "Councilmember Robert White", "DC", "rwhite@dccouncil.us"),
        ( "Councilmember Elissa Silverman", "DC", "esilverman@dccouncil.us"),
        ( "Councilmember Brianne Nadeau", "DC", "bnadeau@dccouncil.us"),
        ( "Councilmember Mary Cheh", "DC", "mcheh@dccouncil.us"),
        ( "Councilmember Brandon Todd", "DC", "btodd@dccouncil.us"),
        ( "Councilmember Charles Allen", "DC", "callen@dccouncil.us"),
        ( "Councilmember Vincent Gray", "DC", "vgray@dccouncil.us"),
        ( "Councilmember Trayon White", "DC", "twhite@dccouncil.us"),

        ( "Mayor Jacob Frey", "MINNEAPOLIS", "Jacob.Frey@minneapolismn.gov"),
        ( "Councilmember Kevin Reich", "MINNEAPOLIS", "kevin.reich@minneapolismn.gov"),
        ( "Councilmember Cam Gordon", "MINNEAPOLIS", "cam.gordon@minneapolismn.gov"),
        ( "Councilmember Steve Fletcher", "MINNEAPOLIS", "steve.fletcher@minneapolismn.gov"),
        ( "Councilmember Phillipe Cunningham", "MINNEAPOLIS", "Phillipe.Cunningham@minneapolismn.gov"),
        ( "Councilmember Jeremiah Ellison", "MINNEAPOLIS", "Jeremiah.Ellison@minneapolismn.gov"),
        ( "Councilmember Abdi Warsame", "MINNEAPOLIS", "Abdi.Warsame@minneapolismn.gov"),
        ( "Councilmember Lisa Goodman", "MINNEAPOLIS", "Lisa.Goodman@minneapolismn.gov"),
        ( "Councilmember Andrea Jenkins", "MINNEAPOLIS", "Andrea.Jenkins@minneapolismn.gov"),
        ( "Councilmember Alondra Cano", "MINNEAPOLIS", "Alondra.Cano@minneapolismn.gov"),
        ( "Councilmember Lisa Bender", "MINNEAPOLIS", "Lisa.Bender@minneapolismn.gov"),
        ( "Councilmember Jeremy Schroeder", "MINNEAPOLIS", "Jeremy.Schroeder@minneapolismn.gov"),
        ( "Councilmember Andrew Johnson", "MINNEAPOLIS", "Andrew.Johnson@minneapolismn.gov"),
        ( "Councilmember Linea Palmisano", "MINNEAPOLIS", "Linea.Palmisano@minneapolismn.gov"),

        ( "Mayor Jim Kenney", "PHILLY", "james.kenney@phila.gov"),
        ( "Council President Darrell Clarke", "PHILLY", "darrell.clarke@phila.gov"),
        ( "Councilmember Mark Squilla", "PHILLY", "mark.squilla@phila.gov"),
        ( "Councilmember Kenyatta Johnson", "PHILLY", "kenyatta.johnson@phila.gov"),
        ( "Councilmember Jamie Gauthier", "PHILLY", "jamie.gauthier@phila.gov"),
        ( "Councilmember Curtis Jones", "PHILLY", "curtis.jones@phila.gov"),
        ( "Councilmember Bobby Henon", "PHILLY", "bobby@bobbyhenon.com"),
        ( "Councilmember Maria Quiñones Sánchez", "PHILLY", "maria.q.sanchez@phila.gov"),
        ( "Councilmember Cindy Bass", "PHILLY", "cindy.bass@phila.gov"),
        ( "Councilmember Cherelle Parker", "PHILLY", "cherelle.parker@phila.gov"),
        ( "Councilmember Brian O'Neill", "PHILLY", "brian.o'neill@phila.gov"),
        ( "Councilmember Kendra Brooks", "PHILLY", "Kendra.Brooks@phila.gov"),
        ( "Councilmember Allan Domb", "PHILLY", "allan.domb@phila.gov"),
        ( "Councilmember Derek Green", "PHILLY", "derek.green@phila.gov"),
        ( "Councilmember Katherine Gilmore Richardson", "PHILLY", "Katherine.G.Richardson@phila.gov"),
        ( "Councilmember Helen Gym", "PHILLY", "helen.gym@phila.gov"),
        ( "Councilmember David Oh", "PHILLY", "david.oh@phila.gov"),
        ( "Councilmember Isaiah Thomas", "PHILLY", "Isaiah.Thomas@phila.gov"),

        ( "Mayor Harry LaRosiliere", "PLANO", "mayor@plano.gov"),
        ( "Mayor Pro Tem Kayci Prince", "PLANO", "kayciprince@plano.gov"),
        ( "Deputy Mayor Pro Tem Anthony Ricciardelli", "PLANO", "aricciardelli@plano.gov"),
        ( "Council Member Maria Tu", "PLANO", "mariatu@plano.gov"),
        ( "Council Member Rick Grady", "PLANO", "rickgrady@plano.gov"),
        ( "Council Member Shelby Williams", "PLANO", "shelbywilliams@plano.gov"),
        ( "Council Member Rick Smith", "PLANO", "ricksmith@plano.gov"),
        ( "Council Member Lily Bao", "PLANO", "lilybao@plano.gov"),

        ( "Council Member Chad West", "DALLAS", "Chad.West@dallascityhall.com"),
        ( "Mayor Pro Tem Adam Medrano", "DALLAS", "adam.medrano@dallascityhall.com"),
        ( "Council Member Casey Thomas, II", "DALLAS", "richard.soto@dallascityhall.com"),
        ( "Council Member Carolyn King Arnold", "DALLAS", "District4@DallasCityHall.com"),
        ( "Council Member Jaime Resendez", "DALLAS", "jaime.resendez@dallascityhall.com"),
        ( "Council Liaison Laura Cadena", "DALLAS", "Laura.Cadena@dallascityhall.com"),
        ( "Council Assistant Yesenia Valdez", "DALLAS", "Yesenia.Valdez@dallascityhall.com"),
        ( "Council Member Tennell Atkins", "DALLAS", "maria.salazar2@dallascityhall.com"),
        ( "Council Member Paula Blackmon", "DALLAS", "District9@DallasCityHall.com"),
        ( "Deputy Mayor Pro Tem B. Adam McGough", "DALLAS", "adam.mcgough@dallascityhall.com"),
        ( "Council Member Lee M. Kleinman", "DALLAS", "sophia.figueroa@dallascityhall.com"),
        ( "Council Member Cara Mendelsohn", "DALLAS", "cara.mendelsohn@dallascityhall.com"),

    ]

def gen_recipients(location):
    recv = []
    for c in county_list:
        recv.append(c)
    return recv
